from typing import Protocol, runtime_checkable


@runtime_checkable
class IPasswordHasher(Protocol):
    def __init__(self, *args, **kwargs) -> None: ...
    def verify(self, password: str, hashed_password: str) -> bool: ...
    def hash(self, password: str) -> str: ...
